name: check dictionary
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
jobs:
  check-dictionary:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: check that dictionary is normalized
        run: |
          tools/normalize.js
          git diff --exit-code
